backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "obsah"
    label: "Obsah stránky"
    files:
      - file: "content.json"
        label: "Hlavní obsah"
        name: "content"
        fields:
          - { label: "Nadpis", name: "title", widget: "string" }
          - { label: "Text", name: "text", widget: "text" }
          - label: "Fotky"
            name: "photos"
            widget: "list"
            summary: "{{fields.photo}}"
            field: { label: "Fotka", name: "photo", widget: "image", required: false }
  - name: "nastaveni"
    label: "Nastavení"
    files:
      - file: "passwords.json"
        label: "Hesla"
        name: "passwords"
        fields:
          - { label: "Admin hash", name: "adminHash", widget: "string", required: false }
          - { label: "View hash", name: "viewHash", widget: "string", required: false }
